spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/city
    username: canngos
    password: 1q2w3e1q2w3e
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

server:
  port: 4567